### ISSUE TITLE
Possible to use myo dongle for mimic websocket itself? 

### ISSUE THREAD

**Issue by onuralpszr** [freehaha/myo4l#2]
Hello ; Is there any possibility to use myo dongle itself ?  Because I don't have ble 4 and also why not use dongle. I mean it should be slower then normal dongle itself. 

Thank you
T

**Comment by freehaha** [comment]
Hi,
If I remember right the [myo-raw](https://github.com/dzhu/myo-raw) already provides the access to myo using the dongle. It doesn't have a websocket interface but the ws protocol is quite simple so it shouldn't be  to hard to implement. 
I'm currently not planning to implement connecting with dongle at the moment but I would gladly take some pull request if you are interested in contributing.
